### ISSUE TITLE
Super resolution model

### ISSUE THREAD

**Issue by FJGEODEV** [olaviinha/NeuralImageSuperResolution#1]
Thanks for the good work. Just wondering which dataset was used to train "the small bsr light model" in your notebook (or referred from Latent_DIffusion repo) for super-resolution? OpenImages as mentioned in the original paper? Thanks.

**Comment by olaviinha** [comment]
I think OpenImages yes, but not sure about the specifics. I only make simplified Colab notebooks for other people's work :-)

All I know is what's in [the source repository](https://github.com/CompVis/latent-diffusion#pretrained-ldms), maybe that'll answer your question.

<img width="693" alt="image" src="https://user-images.githubusercontent.com/50331907/212205427-90233c3a-ae71-4db8-af9d-7af03a670cd1.png">
